Remove references to tackle2-operator from Readme
konveyor/operator pull request #255
Opened 2023-07-25 09:47 UTC by punithnayak

@savitharaghunathan can you please check if it is correct

2023-10-30 15:25 UTC, jmontleon commented
This requires signoff for DCO and there are merge conflicts. Can this be cleaned up and we can go ahead and merge it?

2023-10-30 17:30 UTC, kaovilai requested changes

2023-10-30 17:30 UTC, kaovilai commented on README.md
> +`$ kubectl apply -f https://raw.githubusercontent.com/konveyor/konveyor-operator/v2.0.0-beta.0/tackle-k8s.yaml`
```suggestion
`$ kubectl apply -f https://raw.githubusercontent.com/konveyor/operator/v2.0.0-beta.0/tackle-k8s.yaml`
```

2025-03-19 19:57 UTC, jmontleon commented
Please rebase, signoff, and reopen this PR if you would still like to have it merged.

2025-03-19 19:57 UTC, closed without merging